services:
  nginx_server:
    image: nginx:stable
    ports: 
      - 8000:80
    volumes:
      - ./nginx_server/confs:/etc/nginx/conf.d
      - ./nginx_server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - otree
  otree:
    build: ./otree_server/
    # command: bash -c "while true; do echo 'Hit CTRL+C'; sleep 1; done"
    #command: sh -c "sleep 10; otree prodserver1of2 0.0.0.0:8000 & sleep 10; otree prodserver2of2"
    command: sh -c "otree devserver 0.0.0.0:8000"
    #env_file: ./envs/otree.env
    volumes:
      - ./otree_server:/otree
    depends_on:
      - db
  db:
    image: postgres:15
    env_file: ./envs/postgres.env